---
- name: Add key
  apt_key: id={{spotify_apt_key.id}} keyserver={{spotify_apt_key.keyserver}}

- name: Add repository
  apt_repository: repo={{ spotify_apt_repository.repo }}

- name: Update cache
  apt: update_cache=yes

- name: Install spotify!
  apt: name={{spotify_package.name}}
